### ISSUE TITLE
Retrieval-Augmented Generation (RAG) Integration

### ISSUE THREAD

**Issue by maxwelbarno** [ecitizen-ke/ecitizen-fb-chatbot#49]
**Description**
Retrieval-Augmented Generation (RAG) is the process of optimizing the output of a large language model, so it references an authoritative knowledge base outside of its training data sources before generating a response. Large Language Models (LLMs) are trained on vast volumes of data and use billions of parameters to generate original output for tasks like answering questions, translating languages, and completing sentences. RAG extends the already powerful capabilities of LLMs to specific domains or an organization's internal knowledge base, all without the need to retrain the model. It is a cost-effective approach to improving LLM output so it remains relevant, accurate, and useful in various contexts.

**Tasks**

- [ ] Install the required packages for RAG
               
     - [ ] **Add LangChain Framework:** LangChain provides the tools to connect LLMs with external data sources
 
- [ ] Convert the knowledge base files to PDF
